name = "420th Stats Tracker"
author = "thegamecracks"
prefix = "fdelta_stats"
mainprefix = "z"

[version]
major = 2026
minor = 2
patch = 18

[files]
include = [
    "logo.jpg",
    "README.md",
]

[hemtt.build]
pdrive = "disallow"

[hemtt.check]
pdrive = "ignore"
